---
title: "Gamma Poisson"
author: "Broderick Prows"
date: "2/11/2020"
output: html_document
---

Plot Poisson of `r expression(theta)` = 4.
```{r, fig.align='center'}
plot(0:40, dpois(0:40, lambda = 4), type = 'h', ylab = 'Density', xlab = 'x', main = "Poisson(4)")
```

The Gamma Distribution:
Shape = a 
Rate = b (think wait time)
Scale = beta = 1 / b (think variance)

```{r}
thetas <- seq(0, 8, length=501)
plot(thetas, dgamma(thetas, .5, 1), col="black",
lwd=2.5, main="Gamma(a, b=1) Distributions",
xlab=expression(theta), lty=4, type="l",
ylab=expression(paste(pi, "(", theta, ")", sep="")))
lines(thetas, dgamma(thetas,1,1), col="red",
lwd=2.5, lty=2)
lines(thetas, dgamma(thetas,2,1), col="maroon",
lwd=2,lty=5)
lines(thetas, dgamma(thetas,4,1), col="blue",
lwd=2.5,lty=1)
legend("topright", paste("a=", c(.5,1,2,4),", b=1"),
col=c("black","red","maroon","blue"),
lwd=2.5, lty=c(4,2,5,1))
```

```{r}
thetas <- seq(0, 10, length=501)
plot(thetas, dgamma(thetas, 3, rate=.7), col="black",
lwd=3, main="Gamma(a=3, b) Distributions",
xlab=expression(theta), lty=1, type="l",
ylim=c(0,1.7),
ylab=expression(paste(pi, "(", theta, ")", sep="")))
lines(thetas, dgamma(thetas,3, rate=1.4), col="red",
lwd=3, lty=2)
lines(thetas, dgamma(thetas,3, rate=3.5), col="maroon",
lwd=3,lty=5)
lines(thetas, dgamma(thetas,3,rate=6), col="blue",
lwd=3,lty=4)
legend(4, 1.6, paste("a=3, b=", c(.7,1.4,3.5,6), sep=""),
col=c("black","red","maroon","blue"),
lwd=2, lty=c(1,2,5,4)) 
```

















